language: node_js
services:
node_js:
  - 0.10
before_install:
before_script:
  - npm install -g grunt-cli
  - npm install -d
branches:
  only:
    - master
script:
  - npm test
  - codeclimate < ./coverage/lcov.info
addons:
  code_climate:
    repo_token:
      secure: O2iNJEui8EwF72dfdbQzlnNuA6xlcce9nhoDh0kmK9c6IbSgraPmoM//doT2Fj6Os2Ct4zbiY+XSE0uJvFjofLhLHPXW8AhFWIV2f0WQXMkvjLNAQBiHNA24NYWPKO+E9os9boOkGEW5911uQQUj1Agj569PpEnDXxbtgt5EwVs=
